#!/bin/bash

############################################################################
#
# Copyright (c) 2016 - xenord
#
############################################################################
MENU=xenord_toolkit

  echo -en "\E[32;1m"
  echo -e "============================================================"
  echo -e " Toolkit Linux by xenord                                    "
  echo -e "============================================================"
  echo -e
  echo -e "  0 - cmd per aggiornare lista pacchetti e repository e kernel e rimuove vecchie versioni di kernel"



  if [ $(whoami) != 'root' ]; then
      echo "Give 'Sudo su' and retry";
  else
      echo "Downloading distro's and repository updates.."
      apt-get update && apt-get upgrade && apt-get dist-upgrade && apt-get purge $(deborphan) && apt-get autoremove --purge && apt-get autoclean

  echo -en "\033[1m Finished \033[0m"
  fi
